import Navbar from '@/components/Navbar'

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: May 2026</p>

        <div className="space-y-8 text-gray-600 leading-relaxed text-sm">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Acceptance of terms</h2>
            <p>By accessing or using HuntScouts, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. The platform</h2>
            <p>HuntScouts is a marketplace connecting hunters with licensed outfitters, and a draw strategy tool. We are not an outfitter, hunting guide, or hunting service. We do not employ guides or operate hunts.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Outfitter responsibilities</h2>
            <p>Outfitters represent that they hold all required licenses and permits for every state and species they list. Outfitters are solely responsible for the hunts they conduct. HuntScouts is not liable for the conduct, safety, or outcomes of any guided hunt.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Booking and payments</h2>
            <p>Deposits paid through HuntScouts are non-refundable unless the outfitter cancels the booking. Refund policies for remaining balances are set by the outfitter. HuntScouts charges a service fee (10% standard, 7% for founding outfitters) on each completed booking.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. Scout draw odds data</h2>
            <p>Draw odds data is sourced from state wildlife agencies via public records requests. While we strive for accuracy, we make no guarantees about data completeness or recency. Draw odds data should not be the sole basis for any hunting decision. HuntScouts is not responsible for draw outcomes.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Scout AI</h2>
            <p>Scout AI responses are generated by an AI model and are provided for informational purposes only. AI-generated advice may contain errors. Always verify recommendations against official state agency data before making draw application decisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Subscriptions</h2>
            <p>Scout Pro subscriptions are billed monthly or annually. You may cancel at any time through the billing portal. Cancellation takes effect at the end of the current billing period.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Prohibited uses</h2>
            <p>You may not use HuntScouts to post false listings, manipulate reviews, scrape data, or engage in any fraudulent activity. Violation may result in immediate account termination.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Limitation of liability</h2>
            <p>HuntScouts is provided &quot;as is.&quot; To the maximum extent permitted by law, HuntScouts is not liable for any indirect, incidental, or consequential damages arising from use of the platform.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Contact</h2>
            <p>Questions about these terms: <a href="mailto:support@huntscouts.com" className="text-[#1B4332] underline">support@huntscouts.com</a></p>
          </section>
        </div>
      </main>
    </>
  )
}
