type AgreementParams = {
  bookingId: string
  bookingCreatedAt: string
  hunterName: string
  hunterEmail: string
  hunterIp: string
  outfitterBusinessName: string
  outfitterLicenseNumber: string | null
  listingTitle: string
  species: string[]
  states: string[]
  startDate: string
  endDate: string
  partySize: number
  totalPrice: number
  depositAmount: number | null
  stripePaymentIntentId: string | null
  cancellationPolicy: string
  bookingType: 'instant' | 'request'
  confirmedAt?: string | null
}

const CANCELLATION_TEXT: Record<string, string> = {
  flexible: 'Full refund for cancellations 60+ days before the hunt. Full refund 30–59 days out. 50% refund for cancellations under 30 days. Full refund for force majeure events.',
  moderate: 'Full refund for cancellations 60+ days before the hunt. 50% refund 30–59 days out. No refund for cancellations under 30 days. Full refund for force majeure events.',
  strict: '50% refund for cancellations 60+ days before the hunt. No refund for cancellations under 60 days. Force majeure handled case by case.',
}

export function generateBookingAgreementHtml(p: AgreementParams): string {
  const cancellationText = CANCELLATION_TEXT[p.cancellationPolicy] ?? p.cancellationPolicy
  const confirmNote = p.bookingType === 'instant'
    ? 'Auto-confirmed at booking time.'
    : p.confirmedAt
    ? `Outfitter confirmed on ${new Date(p.confirmedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}.`
    : 'Outfitter confirmation pending.'

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>HuntScouts Booking Agreement — ${p.bookingId}</title>
<style>
  body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 0 30px; color: #111; line-height: 1.6; }
  h1 { font-size: 24px; color: #1B4332; border-bottom: 2px solid #1B4332; padding-bottom: 10px; }
  h2 { font-size: 16px; color: #1B4332; margin-top: 28px; margin-bottom: 6px; }
  .meta { color: #555; font-size: 14px; margin-bottom: 24px; }
  .section { margin-bottom: 20px; }
  .section p { margin: 4px 0; font-size: 14px; }
  .footer { margin-top: 40px; border-top: 1px solid #ccc; padding-top: 16px; font-size: 12px; color: #777; }
  .acceptance { background: #f5f5f5; padding: 16px; border-radius: 6px; font-size: 13px; margin-top: 24px; }
</style>
</head>
<body>
<h1>HuntScouts Booking Agreement</h1>
<div class="meta">
  <p><strong>Agreement date:</strong> ${new Date(p.bookingCreatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  <p><strong>Booking ID:</strong> ${p.bookingId}</p>
</div>

<h2>Parties</h2>
<div class="section">
  <p><strong>Hunter:</strong> ${p.hunterName} &lt;${p.hunterEmail}&gt;</p>
  <p><strong>Outfitter:</strong> ${p.outfitterBusinessName}${p.outfitterLicenseNumber ? ` — License #${p.outfitterLicenseNumber}` : ''}</p>
</div>

<h2>Hunt Details</h2>
<div class="section">
  <p><strong>Listing:</strong> ${p.listingTitle}</p>
  <p><strong>Species:</strong> ${p.species.join(', ')}</p>
  <p><strong>State(s):</strong> ${p.states.join(', ')}</p>
  <p><strong>Dates:</strong> ${p.startDate} to ${p.endDate}</p>
  <p><strong>Party size:</strong> ${p.partySize}</p>
</div>

<h2>Payment Terms</h2>
<div class="section">
  <p><strong>Total price:</strong> $${p.totalPrice.toLocaleString()}</p>
  ${p.depositAmount ? `<p><strong>Deposit paid:</strong> $${p.depositAmount.toLocaleString()} on ${new Date(p.bookingCreatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>` : ''}
  ${p.stripePaymentIntentId ? `<p><strong>Stripe Payment Intent:</strong> ${p.stripePaymentIntentId}</p>` : ''}
  <p><strong>Balance due:</strong> Directly to outfitter per their stated terms.</p>
</div>

<h2>Cancellation Policy</h2>
<div class="section">
  <p>${cancellationText}</p>
</div>

<h2>Platform Terms</h2>
<div class="section">
  <p>This booking was facilitated by HuntScouts (huntscouts.com). HuntScouts is a technology platform connecting hunters with outfitters and is not a party to this hunt. The deposit was processed via Stripe and held in escrow until hunt commencement. By completing this booking, both parties agreed to HuntScouts Terms of Service at huntscouts.com/terms.</p>
</div>

<div class="acceptance">
  <p><strong>Electronic Acceptance</strong></p>
  <p>Hunter accepted booking terms on ${new Date(p.bookingCreatedAt).toLocaleString('en-US')} from IP address ${p.hunterIp}.</p>
  <p>Outfitter: ${confirmNote}</p>
</div>

<div class="footer">
  <p>This document is an automated record generated by HuntScouts at the time of booking. Retain for your records.</p>
</div>
</body>
</html>`
}
